kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.19
  commands:
  - go build -o gospt
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret:
        GITEA
    base_url: https://gitea.asdf.cafe
    files:
      - gospt
    checksum: sha256

trigger:
  event:
    - tag
  when:
      event:
      - tag
      ref:
      - refs/tags/v*
