kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - GOARCH=amd64 GOOS=linux go build -o bin/${BINARY_NAME} main.go
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret:
        GITEA
    base_url: https://gitea.asdf.cafe
    files: bin/${BINARY_NAME}

trigger:
  event:
    - push
    - tag
  when:
      event:
      - tag
      ref:
      - refs/tags/v*
