kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.19
  commands:
  - go build -o gospt
  - ./gospt completion zsh > gospt_zsh
  - ./gospt completion bash > gospt_bash
  - ./gospt completion fish > gospt_fish
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret:
        GITEA_RELEASE
    base_url: https://gitea.asdf.cafe
    files:
      - gospt
      - gospt_zsh
      - gospt_bash
      - gospt_fish
    checksum: sha256

trigger:
  event:
    - tag
  when:
      event:
      - tag
      ref:
      - refs/tags/v*
