pipeline:
  build:
    image: golang:1.19
    commands:
      - go build -o gospt
      - ./gospt completion zsh > gospt_zsh
      - ./gospt completion bash > gospt_bash
      - ./gospt completion fish > gospt_fish

  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      skip_verify: true
      base_url: https://gitea.asdf.cafe
      files:
        - gospt
        - gospt_zsh
        - gospt_bash
        - gospt_fish
      api_key:
        from_secret: GITEA_KEY
      checksum: sha256
    when:
      event: tag
      branch: master

  comment:
    image: mcs94/gitea-comment
    settings:
      gitea_address: https://gitea.asdf.cafe
      gitea_token:
        from_secret: GITEA_KEY
      comment: >
        ✅ Build ${CI_BUILD_EVENT} of `${CI_REPO_NAME}` has status `${CI_BUILD_STATUS}`.

        📝 Commit by ${CI_COMMIT_AUTHOR} on `${CI_COMMIT_BRANCH}`:

        `${CI_COMMIT_MESSAGE}`

        🌐 ${CI_BUILD_LINK}
    when:
      event: [pull_request]
