pipeline:
  build:
    image: golang:1.19
    commands:
      - go build -o gospt
      - ./gospt completion zsh > gospt_zsh
      - ./gospt completion bash > gospt_bash
      - ./gospt completion fish > gospt_fish
