pipeline:
  build:
    image: golang:1.19
    commands:
      - go build -o gospt
      - ./gospt completion zsh > gospt_zsh
      - ./gospt completion bash > gospt_bash
      - ./gospt completion fish > gospt_fish

  publish:
    when:
      event: tag
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: http://Gitea:2385
      files:
        - gospt
        - gospt_zsh
        - gospt_bash
        - gospt_fish
      api_key:
        from_secret: GITEA_KEY
      checksum: sha256
